[project]
name = "backend-foundations"
version = "0.1.0"
description = ""
authors = [
    {name = "jhonjto",email = "jhon1985t@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "backend-foundations"
version = "0.1.0"
description = ""
authors = ["jhonjto <jhon1985t@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = ">=0.121.1,<0.122.0"
uvicorn = {version = ">=0.38.0,<0.39.0", extras = ["standard"]}
sqlalchemy = ">=2.0.45,<3.0.0"
psycopg = {version = ">=3.3.2,<4.0.0", extras = ["binary"]}
email-validator = ">=2.0,<3.0"
alembic = "^1.17.2"
pydantic-settings = "^2.12.0"
redis = {extras = ["hiredis"], version = "^7.1.0"}
confluent-kafka = "^2.12.2"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
passlib = {version = "^1.7.4", extras = ["argon2"]}
argon2-cffi = "^23.1.0"
python-multipart = "^0.0.21"
grpcio = "^1.76.0"
grpcio-tools = "^1.76.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.0"
black = "^25.11.0"
ruff = "^0.14.4"
pre-commit = "^4.4.0"
httpx = "^0.28.1"
pytest-asyncio = "^1.3.0"

[tool.black]
line-length = 88
target-version = ["py311", "py312", "py313"]

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
pythonpath = ["."]
