"""create users table

Revision ID: 910081a8f003
Revises:
Create Date: 2025-12-30 09:51:06.007703

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "910081a8f003"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
